/*
**	Copyright 2026 İlyas Akın
**	Additional terms under GNU GPL section 7 apply: see LICENSE.md.
**
**	This program is free software: you can redistribute it and/or modify
**	it under the terms of the GNU General Public License as published by
**	the Free Software Foundation, either version 3 of the License, or
**	(at your option) any later version.
**
**	This program is distributed in the hope that it will be useful,
**	but WITHOUT ANY WARRANTY; without even the implied warranty of
**	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**	GNU General Public License for more details.
**
**	You should have received a copy of the GNU General Public License
**	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

// Written by Tools/d3d9posix_check.py --write-undefs from Platform/D3D9Posix.h and D3D9PosixMath.h;
// rerun it after changing either.  Every macro those headers define, undefined after the SDK's
// d3d9.h so that the POSIX headers can define them again inside namespace zhposix (D3D12Bridge.h).

#undef D3DPS_VERSION
#undef D3DVS_VERSION
#undef D3D_SDK_VERSION
#undef D3DADAPTER_DEFAULT
#undef D3DDP_MAXTEXCOORD
#undef D3DCOLOR_ARGB
#undef D3DCOLOR_RGBA
#undef D3DCOLOR_XRGB
#undef D3D_OK
#undef D3DERR_WRONGTEXTUREFORMAT
#undef D3DERR_UNSUPPORTEDCOLOROPERATION
#undef D3DERR_UNSUPPORTEDCOLORARG
#undef D3DERR_UNSUPPORTEDALPHAOPERATION
#undef D3DERR_UNSUPPORTEDALPHAARG
#undef D3DERR_TOOMANYOPERATIONS
#undef D3DERR_CONFLICTINGTEXTUREFILTER
#undef D3DERR_UNSUPPORTEDFACTORVALUE
#undef D3DERR_CONFLICTINGRENDERSTATE
#undef D3DERR_UNSUPPORTEDTEXTUREFILTER
#undef D3DERR_CONFLICTINGTEXTUREPALETTE
#undef D3DERR_DRIVERINTERNALERROR
#undef D3DERR_NOTFOUND
#undef D3DERR_MOREDATA
#undef D3DERR_DEVICELOST
#undef D3DERR_DEVICENOTRESET
#undef D3DERR_NOTAVAILABLE
#undef D3DERR_OUTOFVIDEOMEMORY
#undef D3DERR_INVALIDDEVICE
#undef D3DERR_INVALIDCALL
#undef D3DERR_DRIVERINVALIDCALL
#undef D3DERR_WASSTILLDRAWING
#undef D3DTS_WORLDMATRIX
#undef D3DTS_WORLD
#undef D3DTS_WORLD1
#undef D3DTS_WORLD2
#undef D3DTS_WORLD3
#undef D3DTSS_TCI_PASSTHRU
#undef D3DTSS_TCI_CAMERASPACENORMAL
#undef D3DTSS_TCI_CAMERASPACEPOSITION
#undef D3DTSS_TCI_CAMERASPACEREFLECTIONVECTOR
#undef D3DTSS_TCI_SPHEREMAP
#undef D3DTA_SELECTMASK
#undef D3DTA_DIFFUSE
#undef D3DTA_CURRENT
#undef D3DTA_TEXTURE
#undef D3DTA_TFACTOR
#undef D3DTA_SPECULAR
#undef D3DTA_TEMP
#undef D3DTA_CONSTANT
#undef D3DTA_COMPLEMENT
#undef D3DTA_ALPHAREPLICATE
#undef D3DWRAP_U
#undef D3DWRAP_V
#undef D3DWRAP_W
#undef D3DCOLORWRITEENABLE_RED
#undef D3DCOLORWRITEENABLE_GREEN
#undef D3DCOLORWRITEENABLE_BLUE
#undef D3DCOLORWRITEENABLE_ALPHA
#undef D3DCLEAR_TARGET
#undef D3DCLEAR_ZBUFFER
#undef D3DCLEAR_STENCIL
#undef D3DUSAGE_RENDERTARGET
#undef D3DUSAGE_DEPTHSTENCIL
#undef D3DUSAGE_WRITEONLY
#undef D3DUSAGE_SOFTWAREPROCESSING
#undef D3DUSAGE_DONOTCLIP
#undef D3DUSAGE_POINTS
#undef D3DUSAGE_RTPATCHES
#undef D3DUSAGE_NPATCHES
#undef D3DUSAGE_DYNAMIC
#undef D3DUSAGE_AUTOGENMIPMAP
#undef D3DLOCK_READONLY
#undef D3DLOCK_NOSYSLOCK
#undef D3DLOCK_NOOVERWRITE
#undef D3DLOCK_DISCARD
#undef D3DLOCK_DONOTWAIT
#undef D3DLOCK_NO_DIRTY_UPDATE
#undef D3DCURSOR_IMMEDIATE_UPDATE
#undef D3DCREATE_FPU_PRESERVE
#undef D3DCREATE_MULTITHREADED
#undef D3DCREATE_PUREDEVICE
#undef D3DCREATE_SOFTWARE_VERTEXPROCESSING
#undef D3DCREATE_HARDWARE_VERTEXPROCESSING
#undef D3DCREATE_MIXED_VERTEXPROCESSING
#undef D3DPRESENT_INTERVAL_DEFAULT
#undef D3DPRESENT_INTERVAL_ONE
#undef D3DPRESENT_INTERVAL_TWO
#undef D3DPRESENT_INTERVAL_THREE
#undef D3DPRESENT_INTERVAL_FOUR
#undef D3DPRESENT_INTERVAL_IMMEDIATE
#undef D3DPRESENT_RATE_DEFAULT
#undef D3DPRESENTFLAG_LOCKABLE_BACKBUFFER
#undef D3DSGR_NO_CALIBRATION
#undef D3DSGR_CALIBRATE
#undef D3DFVF_RESERVED0
#undef D3DFVF_POSITION_MASK
#undef D3DFVF_XYZ
#undef D3DFVF_XYZRHW
#undef D3DFVF_XYZB1
#undef D3DFVF_XYZB2
#undef D3DFVF_XYZB3
#undef D3DFVF_XYZB4
#undef D3DFVF_XYZB5
#undef D3DFVF_XYZW
#undef D3DFVF_NORMAL
#undef D3DFVF_PSIZE
#undef D3DFVF_DIFFUSE
#undef D3DFVF_SPECULAR
#undef D3DFVF_TEXCOUNT_MASK
#undef D3DFVF_TEXCOUNT_SHIFT
#undef D3DFVF_TEX0
#undef D3DFVF_TEX1
#undef D3DFVF_TEX2
#undef D3DFVF_TEX3
#undef D3DFVF_TEX4
#undef D3DFVF_TEX5
#undef D3DFVF_TEX6
#undef D3DFVF_TEX7
#undef D3DFVF_TEX8
#undef D3DFVF_LASTBETA_UBYTE4
#undef D3DFVF_LASTBETA_D3DCOLOR
#undef D3DFVF_TEXTUREFORMAT2
#undef D3DFVF_TEXTUREFORMAT1
#undef D3DFVF_TEXTUREFORMAT3
#undef D3DFVF_TEXTUREFORMAT4
#undef D3DFVF_TEXCOORDSIZE3
#undef D3DFVF_TEXCOORDSIZE2
#undef D3DFVF_TEXCOORDSIZE4
#undef D3DFVF_TEXCOORDSIZE1
#undef D3DCAPS2_FULLSCREENGAMMA
#undef D3DDEVCAPS_HWTRANSFORMANDLIGHT
#undef D3DDEVCAPS_NPATCHES
#undef D3DPMISCCAPS_COLORWRITEENABLE
#undef D3DPRASTERCAPS_FOGRANGE
#undef D3DPRASTERCAPS_DEPTHBIAS
#undef D3DPTEXTURECAPS_CUBEMAP
#undef D3DPTFILTERCAPS_MINFLINEAR
#undef D3DPTFILTERCAPS_MINFANISOTROPIC
#undef D3DPTFILTERCAPS_MIPFLINEAR
#undef D3DPTFILTERCAPS_MAGFLINEAR
#undef D3DPTFILTERCAPS_MAGFANISOTROPIC
#undef D3DTEXOPCAPS_DISABLE
#undef D3DTEXOPCAPS_SELECTARG1
#undef D3DTEXOPCAPS_SELECTARG2
#undef D3DTEXOPCAPS_MODULATE
#undef D3DTEXOPCAPS_MODULATE2X
#undef D3DTEXOPCAPS_MODULATE4X
#undef D3DTEXOPCAPS_ADD
#undef D3DTEXOPCAPS_ADDSIGNED
#undef D3DTEXOPCAPS_ADDSIGNED2X
#undef D3DTEXOPCAPS_SUBTRACT
#undef D3DTEXOPCAPS_ADDSMOOTH
#undef D3DTEXOPCAPS_BLENDDIFFUSEALPHA
#undef D3DTEXOPCAPS_BLENDTEXTUREALPHA
#undef D3DTEXOPCAPS_BLENDFACTORALPHA
#undef D3DTEXOPCAPS_BLENDTEXTUREALPHAPM
#undef D3DTEXOPCAPS_BLENDCURRENTALPHA
#undef D3DTEXOPCAPS_PREMODULATE
#undef D3DTEXOPCAPS_MODULATEALPHA_ADDCOLOR
#undef D3DTEXOPCAPS_MODULATECOLOR_ADDALPHA
#undef D3DTEXOPCAPS_MODULATEINVALPHA_ADDCOLOR
#undef D3DTEXOPCAPS_MODULATEINVCOLOR_ADDALPHA
#undef D3DTEXOPCAPS_BUMPENVMAP
#undef D3DTEXOPCAPS_BUMPENVMAPLUMINANCE
#undef D3DTEXOPCAPS_DOTPRODUCT3
#undef D3DTEXOPCAPS_MULTIPLYADD
#undef D3DTEXOPCAPS_LERP
#undef D3DDECL_END
